### PR TITLE
Spelling mistakes on Axminster blog post

### PR DESCRIPTION
**Pull request by graymalkin**
Axminster Tools & Machinery is spelled as in Axminster in Devon, the town in which they are based.

Now I've read this more carefully this reads a bit like a clumsy advert placement on our blog, and I am sort-of against that. The person changes from "our members went" to "we enjoyed" before and after the photos.

Perhaps we could get some of the members who went to write about their experiences rather than just placing some token "it was nice" text in followed by a list of courses. We should also be upfront about the prices.

### CODE REVIEW

**Review by egelmex — APPROVED** [review]

**Review by egelmex — CHANGES_REQUESTED** [review]
Seems to be still live on staging?

**Comment by willfurnell** [comment]
Shall we make this unpublished for now so it doesn't show on live? Edit: I see that draft has been set to true - weird that isn't reflected on staging.

**Comment by egelmex** [comment]
Sure.

**Comment by graymalkin** [comment]
Fixed with #49

**Pull request closed without merging**
