### PR TITLE
Change deprecated Now in footer for current year

### PR DESCRIPTION
**Pull request by willfurnell**

### CODE REVIEW

**Comment by willfurnell** [comment]
I can't see the pipeline execution to see why the build failed - but am confused as Hugo served it fine on my local machine.

**Comment by graymalkin** [comment]
```
ERROR: 2018/02/26 10:16:52 template.go:472: template: theme/partials/footer.html:8: function "now" not defined
```

**Comment by graymalkin** [comment]
I can't remember how we get hugo onto the build server. It might be from debian, rather than `go get`

**Comment by graymalkin** [comment]
Got it, I had to push up the version of hugo it fetched. We've moved from `0.16` to `0.37`.

**Review by graymalkin — APPROVED** [review]
Uncontroversial.

**Pull request merged**
